# Generated by Django 3.2.25 on 2024-08-22 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_receipe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receipe',
            new_name='Recipe',
        ),
    ]
